experimental_setup: "direct_prediction"

model:
  in_channels: 1
  out_channels: 1
  use_md_reg: true
  md_reg_weight: 0.001
  
data:
  images_dir: "G:/CM_datasets/images"
  confidence_maps_dir: "G:/CM_datasets/ultranerf"

train:
  lr: 1e-5
  batch_size: 32
  max_epochs: 30
  limit_train_batches: 1.0
  limit_val_batches: 1.0

logger:
  save_dir: "logs"
  name: "DirectPredictionModuleWithMDReg"
  num_images_to_log: 4

callbacks:
  model_checkpoint:
    monitor: "val_loss"
  early_stopping:
    monitor: "val_loss"
    patience: 3

trainer:
  enable_checkpointing: true
  accelerator: "gpu"
  devices: 1
